#add_static_link_extension(delta)
#add_static_link_extension(duckdb)
#add_static_link_extension(fts)
#add_static_link_extension(httpfs)
#add_static_link_extension(iceberg)
#add_static_link_extension(json)
#add_static_link_extension(postgres)
#add_static_link_extension(sqlite)
#add_static_link_extension(unity_catalog)
#add_static_link_extension(vector)

if(${BUILD_WASM})
    message(STATUS "Building for WASM, extension static linking is enabled by default")
    add_static_link_extension(fts)
    add_static_link_extension(json)
    add_static_link_extension(vector)
endif()

if(__ANDROID__)
    message(STATUS "Building for Android, extension static linking is enabled by default")
    add_static_link_extension(fts)
    add_static_link_extension(json)
    add_static_link_extension(vector)
endif()
