blank_issues_enabled: true
contact_links:
  - name: Discord Community Support
    url: https://discord.gg/VtX2gw9Rug
    about: Please ask questions that involve detailed discussions to the Discord community here.