name: Performance optimization suggestion
description: Suggestion a new performance optimization idea for Kuzu
title: "Optimization: "
labels: [performance optimization]
body:
  - type: markdown
    attributes:
      value: |
        Share a new idea for improving Kuzu's performance.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the idea and why it would be useful.
    validations:
      required: true
