version: '3'
services:
  file-server:
    image: kuzudb/extension-repo
    pull_policy: always
    ports:
      - "8081:80"
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
