/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tools_java_api_HelloWorldJNI */

#ifndef _Included_tools_java_api_HelloWorldJNI
#define _Included_tools_java_api_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tools_java_api_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tools_java_1api_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
