@prefix = http://localhost:3110

@path_to_serialized_data = ...

@path_to_serialized_query_plan = ...

### Load the serialized graph data from the path.
#   Method:
#       POST
#   URL:
#       /load
#   DataParams:
#       <path_to_serialized_data>

POST {{prefix}}/load
content-type: text/plain;charset=UTF-8

{{path_to_serialized_data}}

### Execute a query plan.
#   Method:
#       POST
#   URL:
#       /execute
#   DataParams:
#       <path_to_serialized_query_plan>
#       <numThreads>

POST {{prefix}}/execute
content-type: text/plain;charset=UTF-8

{{path_to_serialized_query_plan}}
4


### Gets debug information about the database.
#   Method:
#       GET
#   URL:
#       /graphDebugInfo

GET {{prefix}}/graphDebugInfo
content-type: text/plain;charset=UTF-8


### Return a list of all API endpoints with description and usage.
#   Method:
#       GET
#   URL:
#       /help

GET {{prefix}}/help
