name: CI-Ubuntu-20.04-LTS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ubuntu-2004-build-test:
    name: ubuntu-20.04 build & test
    runs-on: ubuntu-20.04
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - uses: actions/checkout@v3

      - name: Ensure Python dependencies
        run: |
          pip install torch~=2.0.0 --extra-index-url https://download.pytorch.org/whl/cpu
          pip install --user -r tools/python_api/requirements_dev.txt -f https://data.pyg.org/whl/torch-2.0.0+cpu.html

      - name: Build
        run: make release NUM_THREADS=$(nproc)

      - name: Test
        run: make test NUM_THREADS=$(nproc)

      - name: Python test
        run: make pytest NUM_THREADS=$(nproc)

  macos-build-test:
    name: macos build & test
    strategy:
      matrix:
        runner: [macos-11, macos-12]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ensure Python dependencies
        run: |
          pip install torch~=2.0.0 --extra-index-url https://download.pytorch.org/whl/cpu
          pip install --user -r tools/python_api/requirements_dev.txt -f https://data.pyg.org/whl/torch-2.0.0+cpu.html

      - name: Build
        run: make release NUM_THREADS=$(sysctl -n hw.physicalcpu)

      - name: Test
        run: make test NUM_THREADS=$(sysctl -n hw.physicalcpu)

      - name: Python test
        run: make pytest NUM_THREADS=$(sysctl -n hw.physicalcpu)

  windows-build-test:
    name: windows build & test
    strategy:
      matrix:
        runner: [windows-2019, windows-2022]
    runs-on: ${{ matrix.runner }}
    steps:
      - run: |
          mkdir C:\kuzu
          git clone https://github.com/kuzudb/kuzu.git C:\kuzu
          cd C:\kuzu
          git switch ${{ github.ref_name }}

      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Ensure Python dependencies
        shell: cmd
        working-directory: C:\kuzu
        run: |
          pip install torch~=2.0.0 --extra-index-url https://download.pytorch.org/whl/cpu
          pip install --user -r tools\python_api\requirements_dev.txt -f https://data.pyg.org/whl/torch-2.0.0+cpu.html

      - name: Build
        shell: cmd
        working-directory: C:\kuzu
        run: make release NUM_THREADS=%NUMBER_OF_PROCESSORS%

      - name: Test
        shell: cmd
        working-directory: C:\kuzu
        run: make test NUM_THREADS=%NUMBER_OF_PROCESSORS%

      - name: Python test
        shell: cmd
        working-directory: C:\kuzu
        run: make pytest NUM_THREADS=%NUMBER_OF_PROCESSORS%
