name: Generate-Python-Documents

on: workflow_dispatch

jobs:
  generate-python-documents:
    runs-on: kuzu-self-hosted-linux-building
    steps:
      - uses: actions/checkout@v3

      - name: Generate documents
        run: /home/runner/.local/bin/pydoc-markdown -I tools/python_api/src_py/  --verbose > python_docs.md

      - uses: actions/upload-artifact@v3
        with:
          name: kuzu-python_docs
          path: python_docs.md

      - name: Clean up
        run: rm -rf python_docs.md
