name: Get Extensions from Dockerhub
on:
  workflow_dispatch:
  workflow_call:

jobs:
  get-dockerhub-extensions:
    runs-on: ubuntu-22.04
    steps:
      - name: Free disk space on Ubuntu runner
        uses: kfir4444/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
          
      - name: Pull dockerhub extensions and run container
        run: |
          docker pull kuzudb/extension-repo:latest
          docker run --rm -d --name kuzu-extensions kuzudb/extension-repo:latest tail -f /dev/null
      
      - name: Copy dockerhub extensions
        run: |
          mkdir ./dockerhub-extensions
          docker cp kuzu-extensions:/usr/share/nginx/html ./dockerhub-extensions
          sudo chown -R $USER:$USER dockerhub-extensions
          sudo chmod -R 755 dockerhub-extensions
          mv dockerhub-extensions/html/dataset dockerhub-extensions/dataset
          mv dockerhub-extensions/html/ dockerhub-extensions/releases

      - name: Upload dockerhub extensions
        uses: actions/upload-artifact@v4
        with:
          name: dockerhub-extensions
          path: dockerhub-extensions
