name: Get Extensions from GHCR
on:
  workflow_dispatch:
  workflow_call:

jobs:
  get-ghcr-extensions:
    runs-on: ubuntu-22.04
    steps:
      - name: Free disk space on Ubuntu runner
        uses: kfir4444/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
          
      - name: Pull ghcr extensions and run container
        run: |
          docker pull ghcr.io/kuzudb/extension-repo:latest
          docker run --rm -d --name kuzu-extensions ghcr.io/kuzudb/extension-repo:latest tail -f /dev/null
      
      - name: Copy ghcr extensions
        run: |
          mkdir ./ghcr-extensions
          docker cp kuzu-extensions:/usr/share/nginx/html ./ghcr-extensions
          sudo chown -R $USER:$USER ghcr-extensions
          sudo chmod -R 755 ghcr-extensions
          mv ghcr-extensions/html/dataset ghcr-extensions/dataset
          mv ghcr-extensions/html/ ghcr-extensions/releases

      - name: Upload ghcr extensions
        uses: actions/upload-artifact@v4
        with:
          name: ghcr-extensions
          path: ghcr-extensions
