name: Build Mac Node.js Module

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false
env:
  PIP_BREAK_SYSTEM_PACKAGES: 1

jobs:
  build-mac-nodejs-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          pip3 install packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Create Node.js source distribution
        working-directory: tools/nodejs_api
        run: |
          rm -rf kuzu-source.tar.gz package *.node
          node package

      - name: Extract tarball
        working-directory: tools/nodejs_api
        run: tar -xvzf kuzu-source.tar.gz

      - name: Build Node.js native module for Apple Silicon
        working-directory: tools/nodejs_api/package
        run: npm i
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
          ARCHFLAGS: "-arch arm64"

      - name: Move Node.js native module
        working-directory: tools/nodejs_api/
        run: mv package/kuzujs.node kuzujs-darwin-arm64.node

      - uses: actions/upload-artifact@v4
        with:
          name: mac-nodejs-module-arm64
          path: tools/nodejs_api/kuzujs-darwin-*.node

      - name: Clean up
        working-directory: tools/nodejs_api/
        run: rm -rf package

  build-mac-nodejs-x86_64:
    runs-on: self-hosted-mac-x64
    steps:
      - uses: actions/checkout@v4

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          pip3 install packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Create Node.js source distribution
        working-directory: tools/nodejs_api
        run: |
          rm -rf kuzu-source.tar.gz package *.node
          node package

      - name: Extract tarball
        working-directory: tools/nodejs_api
        run: tar -xvzf kuzu-source.tar.gz

      - name: Build Node.js native module for Intel
        working-directory: tools/nodejs_api/package
        run: npm i
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
          ARCHFLAGS: "-arch x86_64"

      - name: Move Node.js native module
        working-directory: tools/nodejs_api/
        run: mv package/kuzujs.node kuzujs-darwin-x64.node

      - uses: actions/upload-artifact@v4
        with:
          name: mac-nodejs-module-x86_64
          path: tools/nodejs_api/kuzujs-darwin-*.node

      - name: Clean up
        working-directory: tools/nodejs_api/
        run: rm -rf package
