name: Multiplatform Build and Test

env:
  USE_EXISTING_BINARY_DATASET: 1
  PIP_BREAK_SYSTEM_PACKAGES: 1

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  generate-binary-demo:
    runs-on: kuzu-self-hosted-testing
    env:
      NUM_THREADS: 32
      GEN: Ninja
      CC: gcc
      CXX: g++
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make release

      - name: Generate datasets
        run: bash scripts/generate_binary_demo.sh

      - name: Upload binary-demo
        uses: actions/upload-artifact@v4
        with:
          name: binary-demo
          path: dataset/binary-demo

  rhel-fedora-build-test:
    strategy:
      matrix:
        image: ["rockylinux:8", "rockylinux:9"]
      fail-fast: false
    name: ${{ matrix.image }}
    needs: [generate-binary-demo]
    runs-on: ubuntu-24.04
    container:
      image: ${{ matrix.image }}
    env:
      CC: gcc
      CXX: g++
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk
      HOME: /root
    steps:
      - name: Enable EPEL
        continue-on-error: true
        if: ${{ matrix.image == 'rockylinux:8' || matrix.image ==  'rockylinux:9' }}
        run: |
          dnf update -y
          dnf install -y epel-release
          dnf update -y

      - name: Enable SHA-1 on Rocky Linux 9
        continue-on-error: true
        if: matrix.image == 'rockylinux:9'
        run: update-crypto-policies --set LEGACY

      - name: Install packages
        continue-on-error: true
        run: |
          curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
          dnf install -y git cmake ${{ (matrix.image == 'rockylinux:8' || matrix.image ==  'rockylinux:9') && 'gcc-toolset-12' || 'gcc gcc-c++ python3-devel' }} java-17-openjdk-devel nodejs

      - name: Enable gcc-toolset-12
        if: ${{ matrix.image == 'rockylinux:8' || matrix.image ==  'rockylinux:9' }}
        continue-on-error: true
        run: |
          source /opt/rh/gcc-toolset-12/enable
          echo $PATH >> $GITHUB_PATH

      - name: Set up Python 3.9 on RockyLinux
        if: ${{ matrix.image == 'rockylinux:8' || matrix.image ==  'rockylinux:9' }}
        continue-on-error: true
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - uses: actions/checkout@v4
        continue-on-error: true

      - name: Download binary-demo
        uses: actions/download-artifact@v4
        with:
          name: binary-demo
          path: ${{ github.workspace }}/dataset/binary-demo

      - name: Ensure Python dependencies
        continue-on-error: true
        run: |
          python3 -m venv /opt/venv
          source /opt/venv/bin/activate
          pip3 install torch~=2.6.0 --extra-index-url https://download.pytorch.org/whl/cpu
          pip3 install -r tools/python_api/requirements_dev.txt -f https://data.pyg.org/whl/torch-2.6.0+cpu.html

      - name: Ensure Node.js dependencies
        continue-on-error: true
        working-directory: tools/nodejs_api
        run: npm install --include=dev

      - name: Install Rust
        continue-on-error: true
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-update-default-toolchain
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          $HOME/.cargo/bin/rustup toolchain install 1.81

      - name: Build
        continue-on-error: true
        run: |
          set +e
          make relwithdebinfo NUM_THREADS=$(nproc)
          echo "Build,$?" > status.txt

      - name: Test
        continue-on-error: true
        run: |
          set +e
          make test NUM_THREADS=$(nproc)
          echo "Test,$?" >> status.txt

      - name: Remove ldbc-1
        run: rm -rf dataset/ldbc-1

      - name: C and C++ examples
        continue-on-error: true
        run: |
          set +e
          make example NUM_THREADS=$(nproc)
          echo "C and C++ examples,$?" >> status.txt

      - name: Python test
        continue-on-error: true
        run: |
          set +e
          source /opt/venv/bin/activate
          make pytest NUM_THREADS=$(nproc)
          echo "Python test,$?" >> status.txt

      - name: Node.js test
        continue-on-error: true
        run: |
          set +e
          make nodejstest NUM_THREADS=$(nproc)
          echo "Node.js test,$?" >> status.txt

      - name: Java test
        continue-on-error: true
        run: |
          set +e
          make javatest NUM_THREADS=$(nproc)
          echo "Java test,$?" >> status.txt

      - name: Cleanup
        run: make clean

      - name: Rust share build
        continue-on-error: true
        run: echo $'[workspace]\nmembers = ["tools/rust_api","examples/rust"]\nresolver = "2"' > Cargo.toml

      - name: Rust set env
        continue-on-error: true
        run: echo "CARGO_BUILD_JOBS=$(nproc)" >> $GITHUB_ENV

      - name: Rust test
        continue-on-error: true
        working-directory: tools/rust_api
        run: |
          set +e
          cargo test --release --features arrow
          echo "Rust test,$?" >> ../../status.txt

      - name: Rust example
        continue-on-error: true
        working-directory: examples/rust
        run: |
          set +e
          cargo build --release --features arrow
          echo "Rust example,$?" >> ../../status.txt

      - name: Rename status.txt
        continue-on-error: true
        run: |
          PLATFORM=$(echo ${{ matrix.image }} | tr ':' '-')
          echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
          mv status.txt $PLATFORM.csv

      - uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ${{env.PLATFORM}}
          path: ${{env.PLATFORM}}.csv

  collect-results:
    runs-on: ubuntu-22.04
    env:
      DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      GITHUB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    needs:
      [
        rhel-fedora-build-test,
      ]
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: results

      - name: List artifacts
        run: ls -R results

      - name: Create summary
        run: |
          pip3 install pandas tabulate discord.py
          python3 scripts/multiplatform-test-helper/collect-results.py results
          python3 scripts/multiplatform-test-helper/notify-discord.py results.json

      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results.md
